#!/usr/bin/env python3
"""Generate deterministic Solar Remote host artifacts from a linked ELF."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import cbor2
from elftools.elf.elffile import ELFFile

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "sdk/python/src"))
from solar_remote.manifest import ManifestError, parse_manifest


def read_image(path: Path) -> bytes:
    with path.open("rb") as stream:
        elf = ELFFile(stream)
        section = elf.get_section_by_name(".solar.remote.manifest")
        if section is None:
            section = elf.get_section_by_name("solar_remote_manifest_area")
        if section is None:
            raise ValueError("ELF has no Solar Remote manifest section")
        data = section.data()
    start = data.find(b"SLRM")
    if start < 0 or len(data) < start + 16:
        raise ValueError("manifest section has no valid image")
    total = int.from_bytes(data[start + 12 : start + 16], "little")
    image = data[start : start + total]
    if len(image) != total:
        raise ValueError("truncated manifest image")
    return image


def identifier(value: str) -> str:
    cleaned = "".join(character if character.isalnum() else "_" for character in value)
    if not cleaned or cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned


def annotation(field: dict, schemas: dict[int, dict]) -> str:
    kind = field["kind"]
    base = {
        "bool": "bool",
        "unsigned": "int",
        "signed": "int",
        "float": "float",
        "text": "str",
        "bytes": "bytes",
    }.get(kind)
    if base is None and field["schema"]:
        base = identifier(schemas[field["schema"]]["name"])
    if base is None:
        base = "object"
    return base if field["required"] else f"{base} | None"


def generate(elf: Path, output: Path) -> None:
    parsed = parse_manifest(read_image(elf))
    manifest = parsed.to_dict()
    canonical = cbor2.dumps(manifest, canonical=True)
    digest = parsed.digest.hex()
    output.mkdir(parents=True, exist_ok=True)
    (output / "manifest.cbor").write_bytes(canonical)
    (output / "manifest.bin").write_bytes(parsed.image)
    (output / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )
    (output / "manifest.sha256").write_text(digest + "\n")
    python = [
        "# Generated by Solar Remote; do not edit.",
        f"PROTOCOL = {tuple(manifest['protocol'])!r}",
        f"MANIFEST_SHA256 = bytes.fromhex({digest!r})",
        "SCHEMA_SHA256 = MANIFEST_SHA256",
    ]
    for collection, prefix in (
        ("schemas", "SCHEMA"),
        ("data", "DATA"),
        ("actions", "ACTION"),
        ("topics", "TOPIC"),
        ("streams", "STREAM"),
        ("links", "LINK"),
    ):
        for item in manifest[collection]:
            name = identifier(item["name"]).upper()
            python.append(f"{prefix}_{name} = 0x{item['id']:08X}")
    for capability in manifest["capabilities"]:
        name = f"{capability['domain']}_{capability['endpoint']:08X}_{capability['kind']}".upper()
        python.append(f"CAPABILITY_{name} = {capability!r}")
    (output / "constants.py").write_text("\n".join(python) + "\n")
    models = [
        "# Generated by Solar Remote; do not edit.",
        "from dataclasses import dataclass",
        "from enum import IntEnum",
        "from solar_remote import OpenIntEnum",
        "",
    ]
    schemas = {item["id"]: item for item in manifest["schemas"]}
    for schema in manifest["schemas"]:
        class_name = identifier(schema["name"])
        if schema["shape"] in ("enumeration", "status-code"):
            base = "OpenIntEnum" if schema["open"] else "IntEnum"
            models.append(f"class {class_name}({base}):")
            for value in schema["values"]:
                models.append(
                    f"    {identifier(value['name']).upper()} = {value['value']}"
                )
            models.append("")
        elif schema["shape"] == "object":
            models.extend(
                [
                    "@dataclass(frozen=True, slots=True)",
                    f"class {class_name}:",
                ]
            )
            if not schema["fields"]:
                models.append("    pass")
            else:
                required = [item for item in schema["fields"] if item["required"]]
                optional = [item for item in schema["fields"] if not item["required"]]
                for value in required + optional:
                    default = "" if value["required"] else " = None"
                    models.append(
                        f"    {identifier(value['name'])}: {annotation(value, schemas)}{default}"
                    )
                enum_fields = [
                    value
                    for value in schema["fields"]
                    if value["schema"]
                    and schemas[value["schema"]]["shape"]
                    in ("enumeration", "status-code")
                ]
                if enum_fields:
                    models.extend(["", "    def __post_init__(self):"])
                    for value in enum_fields:
                        enum_model = identifier(schemas[value["schema"]]["name"])
                        name = identifier(value["name"])
                        if value["required"]:
                            models.append(
                                f"        object.__setattr__(self, {name!r}, "
                                f"{enum_model}(self.{name}))"
                            )
                        else:
                            models.extend(
                                [
                                    f"        if self.{name} is not None:",
                                    f"            object.__setattr__(self, {name!r}, "
                                    f"{enum_model}(self.{name}))",
                                ]
                            )
            models.append("")
    (output / "models.py").write_text("\n".join(models) + "\n")
    client = [
        "# Generated by Solar Remote; do not edit.",
        "from dataclasses import asdict, is_dataclass",
        "from collections.abc import Mapping",
        "from solar_remote import AsyncSession",
        "try:",
        "    from . import models",
        "except ImportError:",
        "    import models",
        "",
        "class FirmwareClient:",
        f"    protocol = {tuple(manifest['protocol'])!r}",
        f"    manifest_sha256 = bytes.fromhex({digest!r})",
        "    schema_sha256 = manifest_sha256",
        "",
        "    def __init__(self, session: AsyncSession | None = None):",
        "        self.session = session",
        "",
        "    @staticmethod",
        "    def _model(model, value):",
        "        if isinstance(value, model): return value",
        "        if is_dataclass(value): value = asdict(value)",
        "        if isinstance(value, Mapping): return model(**value)",
        "        return model(value)",
    ]
    for collection, prefix in (
        ("data", "DATA"),
        ("actions", "ACTION"),
        ("topics", "TOPIC"),
        ("streams", "STREAM"),
    ):
        for item in manifest[collection]:
            name = identifier(item["name"]).upper()
            client.append(f"    {prefix}_{name} = 0x{item['id']:08X}")
    for item in manifest["data"]:
        method = identifier(item["name"])
        capabilities = [
            value
            for value in manifest["capabilities"]
            if value["domain"] == "data" and value["endpoint"] == item["id"]
        ]
        if any(value["kind"] == "query" for value in capabilities):
            model = identifier(schemas[item["schema"]]["name"])
            client.extend(
                [
                    "",
                    f"    async def get_{method}(self) -> models.{model}:",
                    '        if self.session is None: raise RuntimeError("client is not bound")',
                    f"        value = await self.session.get(0x{item['id']:08X})",
                    f"        return self._model(models.{model}, value)",
                ]
            )
        if any(value["kind"] == "update" for value in capabilities):
            client.extend(
                [
                    "",
                    f"    async def set_{method}(self, value: models."
                    f"{identifier(schemas[item['schema']]['name'])}) -> None:",
                    '        if self.session is None: raise RuntimeError("client is not bound")',
                    f"        await self.session.set(0x{item['id']:08X}, value)",
                ]
            )
        if any(value["kind"] == "watch" for value in capabilities):
            client.extend(
                [
                    "",
                    f"    async def subscribe_{method}(self, **policy):",
                    '        if self.session is None: raise RuntimeError("client is not bound")',
                    f"        return await self.session.watch(0x{item['id']:08X}, **policy)",
                ]
            )
        if any(value["kind"] == "out_stream" for value in capabilities):
            client.extend(
                [
                    "",
                    f"    async def subscribe_{method}(self, **policy):",
                    '        if self.session is None: raise RuntimeError("client is not bound")',
                    f"        return await self.session.stream(0x{item['id']:08X}, **policy)",
                ]
            )
    for item in manifest["actions"]:
        method = identifier(item["name"])
        request_model = identifier(schemas[item["request_schema"]]["name"])
        response_model = identifier(schemas[item["response_schema"]]["name"])
        client.extend(
            [
                "",
                f"    async def call_{method}(self, value: models.{request_model} | None = None)"
                f" -> models.{response_model}:",
                '        if self.session is None: raise RuntimeError("client is not bound")',
                f"        result = await self.session.call(0x{item['id']:08X}, value)",
                f"        return self._model(models.{response_model}, result)",
            ]
        )
    for item in manifest["topics"]:
        method = identifier(item["name"])
        client.extend(
            [
                "",
                f"    async def subscribe_{method}(self, **policy):",
                '        if self.session is None: raise RuntimeError("client is not bound")',
                f"        return await self.session.topic(0x{item['id']:08X}, **policy)",
            ]
        )
    for item in manifest["streams"]:
        method = identifier(item["name"])
        client.extend(
            [
                "",
                f"    async def subscribe_{method}(self, **policy):",
                '        if self.session is None: raise RuntimeError("client is not bound")',
                f"        return await self.session.stream(0x{item['id']:08X}, **policy)",
            ]
        )
    (output / "client.py").write_text("\n".join(client) + "\n")
    cpp = [
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace solar::remote::generated {",
        f"inline constexpr std::uint8_t protocol_major = {manifest['protocol'][0]};",
        f"inline constexpr std::uint8_t protocol_minor = {manifest['protocol'][1]};",
        "inline constexpr std::array<std::uint8_t, 32> manifest_sha256{"
        + ", ".join(f"0x{digest[index : index + 2]}" for index in range(0, 64, 2))
        + "};",
    ]
    cpp.append("inline constexpr auto schema_sha256 = manifest_sha256;")
    cpp.append("} // namespace solar::remote::generated\n")
    (output / "manifest.hpp").write_text("\n".join(cpp))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--elf", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        generate(args.elf, args.output)
    except (OSError, ValueError, KeyError, ManifestError) as error:
        print(f"solar-remote-generate: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
