"""Independently evolved Solar artifact format versions."""

GENERATOR_VERSION = 1
PROJECT_FORMAT = 1
INTERFACE_FORMAT = 1
IR_FORMAT = 1
LOCK_FORMAT = 1
EFFECTIVE_MANIFEST_FORMAT = 2
COMPATIBILITY_FORMAT = 1
SHIPMENT_FORMAT = 1
REMOTE_PROTOCOL = (1, 2)
