"""Async-first host SDK for Solar Remote."""

from .api import (
    BoundActionEndpoint,
    BoundDataEndpoint,
    BoundOutputEndpoint,
    FrameSubscription,
    Robot,
    UnsupportedOperation,
)
from .channel import AsyncByteChannel
from .chunked import ChunkGap, ChunkReassembler, ReassembledScan, reassemble_chunks
from .client import Client, Hello, Message, Reassembler
from .codec import CodecError, DynamicCodec, UnknownEnumValue
from .descriptors import (
    ActionEndpoint,
    CapabilityDescriptor,
    Catalog,
    DataEndpoint,
    EndpointDescriptor,
    EnumValueDescriptor,
    FieldDescriptor,
    InStreamGroupDescriptor,
    LinkDescriptor,
    ManifestCatalog,
    SchemaDescriptor,
    StreamEndpoint,
    TopicEndpoint,
)
from .frames import Frame, QueuePolicy
from .generated import (
    BuildPolicy,
    GeneratedAction,
    GeneratedData,
    GeneratedInputStream,
    GeneratedOutputStream,
    GeneratedParameter,
    GeneratedSubscription,
    InterfaceMismatch,
    InterfacePolicy,
    coerce_model,
    validate_generated_interface,
)
from .manifest import Manifest, ManifestError, compatibility, parse_manifest
from .models import ModelRegistry, OpenIntEnum
from .protocol import (
    SUBSCRIPTION_DATA_IN_STREAM,
    SUBSCRIPTION_DATA_STREAM,
    SUBSCRIPTION_DATA_WATCH,
    SUBSCRIPTION_STREAM,
    SUBSCRIPTION_TOPIC,
    CollectionDescriptor,
    CollectionPage,
    CollectionQueryPage,
    CreditGrant,
    Envelope,
    FrameDecoder,
    FrameError,
    InStreamClosed,
    InStreamCloseRequest,
    InStreamOpenResponse,
    IntrospectionSummary,
    ManifestChunk,
    ServerInformation,
    SubscriptionPolicy,
    SubscriptionRequest,
    decode_batch,
    decode_frame,
    encode_batch,
    encode_collection_query_request,
    encode_collection_request,
    encode_frame,
)
from .session import (
    ActionError,
    AsyncSession,
    InboundStream,
    PingResult,
    RemoteError,
    SessionClosed,
    Subscription,
)

__all__ = [
    "SUBSCRIPTION_DATA_IN_STREAM",
    "SUBSCRIPTION_DATA_STREAM",
    "SUBSCRIPTION_DATA_WATCH",
    "SUBSCRIPTION_STREAM",
    "SUBSCRIPTION_TOPIC",
    "ActionEndpoint",
    "ActionError",
    "AsyncByteChannel",
    "AsyncSession",
    "BoundActionEndpoint",
    "BoundDataEndpoint",
    "BoundOutputEndpoint",
    "BuildPolicy",
    "CapabilityDescriptor",
    "Catalog",
    "ChunkGap",
    "ChunkReassembler",
    "Client",
    "CodecError",
    "CollectionDescriptor",
    "CollectionPage",
    "CollectionQueryPage",
    "CreditGrant",
    "DataEndpoint",
    "DynamicCodec",
    "EndpointDescriptor",
    "EnumValueDescriptor",
    "Envelope",
    "FieldDescriptor",
    "Frame",
    "FrameDecoder",
    "FrameError",
    "FrameSubscription",
    "GeneratedAction",
    "GeneratedData",
    "GeneratedInputStream",
    "GeneratedOutputStream",
    "GeneratedParameter",
    "GeneratedSubscription",
    "Hello",
    "InStreamCloseRequest",
    "InStreamClosed",
    "InStreamGroupDescriptor",
    "InStreamOpenResponse",
    "InboundStream",
    "InterfaceMismatch",
    "InterfacePolicy",
    "IntrospectionSummary",
    "LinkDescriptor",
    "Manifest",
    "ManifestCatalog",
    "ManifestChunk",
    "ManifestError",
    "Message",
    "ModelRegistry",
    "OpenIntEnum",
    "PingResult",
    "QueuePolicy",
    "ReassembledScan",
    "Reassembler",
    "RemoteError",
    "Robot",
    "SchemaDescriptor",
    "ServerInformation",
    "SessionClosed",
    "StreamEndpoint",
    "Subscription",
    "SubscriptionPolicy",
    "SubscriptionRequest",
    "TopicEndpoint",
    "UnknownEnumValue",
    "UnsupportedOperation",
    "coerce_model",
    "compatibility",
    "decode_batch",
    "decode_frame",
    "encode_batch",
    "encode_collection_query_request",
    "encode_collection_request",
    "encode_frame",
    "parse_manifest",
    "reassemble_chunks",
    "validate_generated_interface",
]
