"""Async-first host SDK for Solar Remote."""

from .client import Client, Hello, Message, Reassembler
from .codec import CodecError, DynamicCodec, UnknownEnumValue
from .connect import connect
from .manifest import Manifest, ManifestError, compatibility, parse_manifest
from .session import (
    ActionError,
    AsyncSession,
    InboundStream,
    RemoteError,
    SessionClosed,
    Subscription,
)

from .protocol import (
    CreditGrant,
    CollectionDescriptor,
    CollectionPage,
    CollectionQueryPage,
    Envelope,
    FrameDecoder,
    FrameError,
    ManifestChunk,
    ServerInformation,
    IntrospectionSummary,
    InStreamClosed,
    InStreamCloseRequest,
    InStreamOpenResponse,
    SUBSCRIPTION_DATA_IN_STREAM,
    SUBSCRIPTION_DATA_STREAM,
    SUBSCRIPTION_DATA_WATCH,
    SUBSCRIPTION_STREAM,
    SUBSCRIPTION_TOPIC,
    SubscriptionPolicy,
    SubscriptionRequest,
    decode_batch,
    decode_frame,
    encode_batch,
    encode_collection_request,
    encode_collection_query_request,
    encode_frame,
)

__all__ = [
    "Client",
    "AsyncSession",
    "ActionError",
    "CodecError",
    "CreditGrant",
    "CollectionDescriptor",
    "CollectionPage",
    "CollectionQueryPage",
    "Envelope",
    "FrameDecoder",
    "FrameError",
    "DynamicCodec",
    "Hello",
    "IntrospectionSummary",
    "InboundStream",
    "InStreamClosed",
    "InStreamCloseRequest",
    "InStreamOpenResponse",
    "Manifest",
    "ManifestChunk",
    "ManifestError",
    "Message",
    "Reassembler",
    "RemoteError",
    "ServerInformation",
    "SessionClosed",
    "SUBSCRIPTION_DATA_STREAM",
    "SUBSCRIPTION_DATA_IN_STREAM",
    "SUBSCRIPTION_DATA_WATCH",
    "SUBSCRIPTION_STREAM",
    "SUBSCRIPTION_TOPIC",
    "SubscriptionPolicy",
    "Subscription",
    "SubscriptionRequest",
    "UnknownEnumValue",
    "compatibility",
    "connect",
    "decode_batch",
    "decode_frame",
    "encode_batch",
    "encode_collection_request",
    "encode_collection_query_request",
    "encode_frame",
    "parse_manifest",
]
